# Generated by Django 4.2.5 on 2023-10-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school_info", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="first_name",
            field=models.CharField(max_length=150),
        ),
    ]
