# Generated by Django 4.2.5 on 2023-10-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school_info", "0002_alter_teacher_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="first_name",
            field=models.CharField(max_length=50),
        ),
    ]
